export interface GeneratedSignal {
  id: string;
  signal_origin: 'polymarket' | 'catalyst_convergence' | 'hybrid';
  market_condition_id: string;
  market_slug: string;
  market_title: string;
  odds_before: number;
  odds_now: number;
  delta_pct: number;
  time_window_minutes: number;
  whale_detected: boolean;
  whale_amount_usd: number | null;
  matched_asset_id: string;
  matched_asset_name: string;
  polarity: 'direct' | 'inverse' | 'context_dependent';
  suggested_action: string;
  suggested_instruments: Array<{
    name: string;
    avanza_id: string;
    leverage: number | null;
    avanza_url: string;
  }>;
  reasoning: string;
  confidence: number;
  requires_judgment: boolean;
  deduplication_key: string;
  verification_status: 'pending' | 'approved' | 'rejected' | 'needs_review';
  verification_score: number;
  verification_reason: string;
  verification_flags: string[];
  verification_source: string;
  verification_record: string | null;
  primary_source_family?: string;
  catalyst_score?: number;
  catalyst_summary?: string;
  execution_replay_gate?: 'open' | 'watch' | 'block' | 'unknown';
  execution_replay_expectancy_pct?: number;
  execution_replay_samples?: number;
  execution_replay_win_rate?: number;
  fusion_p_hat?: number;
  fusion_expectancy_pct?: number;
  fusion_decision?: 'allow' | 'suppress' | 'fallback_phase1';
  fusion_reasons?: string[];
  fusion_suppress_reasons?: string[];
}
